#!/usr/bin/env bash

job_dir=$1
mode=$2
file=$3

find ${job_dir}/chip -name "*[0-9]_${file}" \
  | ${BASE}/bin/util/combine-expression-data ${mode} \
  | grep -v '\<NA\>' > ${job_dir}/combined/${file}
