#!/usr/bin/env bash

set -x

source ${BASE}/lib/env.sh
source ${BASE}/lib/util.sh

dirs="
${WORK_DIR}/raw-qc/combined
${WORK_DIR}/raw-qc-average/combined
"

exclude_sample_list="exclude_sample_list.txt"

for dir in ${dirs}; do sed -n '2,$p' ${dir}/${exclude_sample_list} | awk '{ print $1 }'; done \
  | sort -u > ${EXCLUDE_ALL_PATTERN_FILE}

## Note: Flip logic - look up the "donor" arrays to create a "non-donor" exclude pattern file

{ cat ${EXCLUDE_ALL_PATTERN_FILE}; ${BASE}/bin/util/generate-chip-list donor-array; } \
  | sort -u > ${EXCLUDE_NON_DONOR_PATTERN_FILE}

## Note: Flip logic - look up the "non-donor" arrays to create a donor exclude pattern file

{ cat ${EXCLUDE_ALL_PATTERN_FILE}; ${BASE}/bin/util/generate-chip-list non-donor-array; } \
  | sort -u > ${EXCLUDE_DONOR_PATTERN_FILE}

for dataset in ${DATASETS}; do
  /bin/mkdir -vp ${FILTERED_DATA_DIR}/${dataset}

  ${BASE}/bin/util/copy-data \
    ${RAW_CHIP_LIST} ${WORK_DIR}/common/exclude-${dataset}.txt ${RAW_DATA_DIR} ${FILTERED_DATA_DIR}/${dataset}
done
