#!/usr/bin/env bash

set -x

source ${BASE}/lib/env.sh
source ${BASE}/lib/util.sh

get_chip_barcode() {
  sed -n "${SLURM_ARRAY_TASK_ID}p" ${chip_list}
}

script=$1
data_dir=$2
job_dir=$3
chip_list=$4

chip_barcode=$( get_chip_barcode )

results_dir=${job_dir}/chip/${chip_barcode}/results
qc_dir=${job_dir}/chip/${chip_barcode}/qc

mkdir -p ${results_dir} ${qc_dir}

${BASE}/bin/run-R ${script} ${data_dir} ${results_dir} ${qc_dir} # qc_dir is only implemented in method-a currently

exit $?
