#!/usr/bin/env bash

source ${BASE}/lib/env.sh
source ${BASE}/lib/util.sh

expression_file_specs="
default:control_expression.txt
default:wo_control_expression.txt
lumi:control_expression_lumi.txt
lumi-wo:wo_control_expression_lumi.txt
"

for dataset in ${DATASETS}; do
  for method in $(get_methods ${dataset}); do
    for line in ${expression_file_specs}; do
      mode=$(echo $line | awk -F: '{print $1}')
      file=$(echo $line | awk -F: '{print $2}')

      method_name="method-${method}-step-1-${dataset}"
      job_name="combine-expression-${method_name}"
      job_dir="${WORK_DIR}/${method_name}"

      mkdir -p ${job_dir}/combined

      job_ids=${job_ids}:$(
        sbatch-submit "${job_name}" \
          "--mem=120G --cpus-per-task=4 --time=0-04:00:00" \
          "${BASE}/job/combine-expression" \
            ${job_dir} \
            ${mode} \
            ${file}
      )
    done
  done
done

echo "${job_ids#:}"
