#!/usr/bin/env bash

source ${BASE}/lib/env.sh
source ${BASE}/lib/util.sh

for dataset in ${DATASETS}; do
  for method in ${METHODS}; do
    /bin/cp \
      ${WORK_DIR}/common/BeadArray_phenotype_details-${dataset}.txt \
      ${WORK_DIR}/method-${method}-step-1-${dataset}/combined/BeadArray_phenotype_details.txt

    job_ids=${job_ids}:$(
      sbatch-submit "method-${method}-step-2-${dataset}" \
        "--mem=120G --cpus-per-task=4 --time=7-00:00:00" \
        "${BASE}/bin/run-R" \
        "${BASE}/code/BeadArray-method-${method}-step-2.R" \
        "${WORK_DIR}/method-${method}-step-1-${dataset}/combined" \
        ${GENERATE_PDFS}
    )
  done
done

echo ${job_ids#:}
