#!/usr/bin/env bash

set -x

source ${BASE}/lib/env.sh
source ${BASE}/lib/util.sh

donor_dirs="
donor-1
donor-1_filter
donor-2
donor-2_filter
"

for dataset in ${DATASETS}; do
  if ! in_list ${dataset} ${NORMALIZED_EXCLUDE_DATASETS}; then
    METHODS="$(get_methods ${dataset})" \
      ${BASE}/bin/util/combine-normalized-methods ${dataset}

    for donor_dir in ${donor_dirs}; do
      METHODS="$(get_methods ${dataset})" \
        sbatch-submit "combine-normalized-methods-${dataset}-${donor_dir}" \
          "--mem=32G --cpus-per-task=4 --time=0-04:00:00" \
          "${BASE}/bin/run-R" \
          "${BASE}/code/BeadArray-normalization-compare-methods.R" \
          "${WORK_DIR}/combine-normalized-methods/${dataset}/${donor_dir}"
    done
  else
    echo "$(basename $0): dataset '${dataset}' matches a value in " \
         "\$NORMALIZED_EXCLUDE_DATASETS ($NORMALIZED_EXCLUDE_DATASETS). Skipping." 1>&2
  fi
done

exit 0
