#!/usr/bin/env bash

set -x

source ${BASE}/lib/env.sh
source ${BASE}/lib/util.sh

ensure_dir ${RAW_DATA_DIR}

exclude_file=${WORK_DIR}/common/exclude-data-raw.txt

{ sed -n '2,$p' /hiidata/projects/BeadArray/replaced_samples.txt  | awk -F'\t' '{print $8 "_" $9}';
  cat ${RAW_DATA_EXCLUDE_PATTERNS};
} \
| sort -u > ${exclude_file}

${BASE}/bin/util/copy-data ${RAW_CHIP_LIST} ${exclude_file} ${JINFINITI_DATA_DIR} ${RAW_DATA_DIR}
