#!/usr/bin/env bash

set -x

source ${BASE}/lib/env.sh
source ${BASE}/lib/util.sh

${BASE}/bin/util/generate-phenotype-details \
  /hiidata/projects/BeadArray/cols_added.tsv \
  /hiidata/teddy/data/jinfiniti/gene_expression/map_info.txt \
  > ${WORK_DIR}/common/BeadArray_phenotype_details.txt

for dataset in ${DATASETS}; do
  ${BASE}/bin/util/find-chip-arrays ${BASE}/tmp/data/filtered/${dataset} \
    > ${WORK_DIR}/common/chip-list-filtered-${dataset}.txt

  head -1 ${WORK_DIR}/common/BeadArray_phenotype_details.txt \
    > ${WORK_DIR}/common/BeadArray_phenotype_details-${dataset}.txt

  grep -f ${WORK_DIR}/common/chip-list-filtered-${dataset}.txt ${WORK_DIR}/common/BeadArray_phenotype_details.txt \
    >> ${WORK_DIR}/common/BeadArray_phenotype_details-${dataset}.txt

  wc -l ${WORK_DIR}/common/BeadArray_phenotype_details-${dataset}.txt
done
