#!/usr/bin/env bash

export BASE="$(readlink -f $(readlink -f $(dirname "${BASH_SOURCE}")/..))"

scripts="
BeadArray_approach_a_step_1.R
BeadArray_method_1_step_1.R
BeadArray_method_2_step_1.R
BeadArray_method_3_step_1.R
BeadArray_method_4_step_1.R
BeadArray_method_5_step_1.R
"

expression_file_specs="
default:control_expression.txt
default:wo_control_expression.txt
lumi:control_expression_lumi.txt
lumi:wo_control_expression_lumi.txt
"

for line in ${expression_file_specs}; do
  mode=$(echo $line | awk -F: '{print $1}')
  file=$(echo $line | awk -F: '{print $2}')

  for script in ${scripts}; do
    mkdir -p $BASE/tmp/work/${script}/combined

    mkdir -p $BASE/tmp/log/combine-expression-files

    sbatch \
      --ntasks=1 \
      --job-name="combine-expression-files-${script}-${mode}-${file}" \
      --output="$BASE/tmp/log/combine-expression-files/${script}-${mode}-${file}.log" \
      --mem=120G \
      --cpus-per-task=2 \
      --time=0-02:00:00 \
      --partition=hii02 \
      ${BASE}/sbatch/combine-expression-files ${script} ${mode} ${file}
  done
done
