#!/usr/bin/env bash

BASE="$(readlink -f $(readlink -f $(dirname "${BASH_SOURCE}")/..))"

script_prefixes="
  BeadArray_approach_a
  BeadArray_method_1
  BeadArray_method_2
  BeadArray_method_3
  BeadArray_method_4
  BeadArray_method_5
"

$BASE/bin/util/transform-cols-added \
  /hiidata/projects/BeadArray/cols_added.tsv \
  $BASE/tmp/work/all/exclude-data-filtered.txt \
  > $BASE/tmp/work/all/BeadArray_phenotype_details.txt

for script_prefix in ${script_prefixes}; do
  /bin/cp $BASE/tmp/work/all/BeadArray_phenotype_details.txt $BASE/tmp/work/${script_prefix}_step_1.R/combined

  sbatch \
    --ntasks=1 \
    --job-name="${script_prefix}_step_2.R" \
    --output=$BASE/tmp/log/${script_prefix}_step_2.R.log \
    --mem=120G \
    --cpus-per-task=2 \
    --time=0-16:00:00 \
    --partition=hii02 \
    --wrap="R_LIBS=$HOME/lib/R/3.2.3 $BASE/bin/run-R \
      $BASE/code/${script_prefix}_step_2.R \
      $BASE/tmp/work/${script_prefix}_step_1.R/combined"
done
