#!/usr/bin/env bash

BASE="$(readlink -f $(readlink -f $(dirname "${BASH_SOURCE}")/..))"

cols_added=/hiidata/projects/BeadArray/cols_added.tsv

if ! [[ -f ${cols_added} ]]; then
  echo "cols_added file '${cols_added}' does not exist." 1>&2
  exit 1
fi


